from .user import User
from .course import Course
from .lesson import Lesson
from .material import Material
from .course_material import CourseMaterial
from .chat import Chat
from .message import Message
from .admin import Admin
from .student_course import StudentCourseAssignment